name: CI Pipeline for Microservices

on:
  push:
    branches:
      - main

jobs:
  # Job per eseguire tutti i test unitari sui microservizi individuali
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build e avvia tutti i servizi in modalità detached
      - name: Build and Start All Services
        run: docker compose -f src/docker-compose.yml up --build -d

      # Esegui i test di integrazione puntando al gateway
      - name: Run integration tests with Newman through Gateway
        run: newman run tests/integration.postman_collection.json --env-var "baseUrl=http://localhost:5000"

      # Arresta e rimuove tutti i container dopo i test
      - name: Stop and Remove All Containers
        run: docker compose -f src/docker-compose.yml down