name: CI Pipeline for Microservices

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [calc, string]  # Specifica i microservizi da testare
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Per ciascun microservizio, eseguiamo il build e i test
      - name: Build docker image for ${{ matrix.service }}
        run: docker build -t ${{ matrix.service }}-test -f src/${{ matrix.service }}/Dockerfile_test src/${{ matrix.service }}

      - name: Run container for ${{ matrix.service }} in detached mode
        run: docker run -d --name ${{ matrix.service }}_container ${{ matrix.service }}-test

      - name: Run unit tests with Newman for ${{ matrix.service }}
        run: newman run tests/${{ matrix.service }}_ut.postman_collection.json

      - name: Stop and remove the container
        run: docker stop ${{ matrix.service }}_container && docker rm ${{ matrix.service }}_container

  build_services:
      runs-on: ubuntu-latest
      needs: unit_tests  # Esegui questo job solo se unit_tests ha successo
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
  
        - name: Set up Docker
          uses: docker/setup-buildx-action@v3
  
        - name: Run docker compose build
          run: docker-compose -f src/docker-compose.yml build

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_services  # Esegui questo job solo se build_services ha successo
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run docker compose up in detached mode
        run: docker-compose -f src/docker-compose.yml up -d

      - name: Run integration tests with Newman
        run: newman run tests/integration.postman_collection.json

      - name: Stop and remove all containers
        run: docker-compose -f src/docker-compose.yml down



        
