name: CI Pipeline for Microservices
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [calc, string]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js for Newman
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run unit tests with Newman for ${{ matrix.service }}
        run: |
          newman run tests/${{ matrix.service }}_ut.postman_collection.json

  build_services:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker containers
        run: docker-compose -f src/docker-compose.yml up --build -d

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_services
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js for Newman
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run integration tests with Newman
        run: newman run tests/integration.postman_collection.json
